### ISSUE TITLE
Two hubs and home appliance activities

### ISSUE THREAD

**Issue by spottaaja1** [Khazul/roon-extension-deep-harmony-release#3]
Hello!

I have a setup with two Harmony hubs and two remotes. The other hub has two types of activities: A/V activities and one activity for toggling Philips Hue Smart Plug on/off. The smart plug activity is independent of the other activities on the hub, ie. I can have my TV activity on and switch the smart plug activity on and off. Maybe this is what gets Deep Harmony confused.

If I reset DH configuration and remake all the settings, the smart plug activity works for a while before it stops working. DH seems to think the activity is off, though it isn't. No amount of convincing or activity switching is enough to convince it otherwise.

As a result, my Roon Zone - relying on the smart plug activity to switch on the audio gear - stays paused, thus making me not hear any music.

Please advice: bug, feature or dumb user?

**Comment by Khazul** [comment]
Deep Harmony does not in any way impact how Harmony interprets its devices and activities. It merely asks harmony what activity is currently selected (if any) and if required, tell its to change to the required activity (for Roon).

Therefore any control of power switches etc needs to be checked in Harmony independently of Deep harmony (ie from your remote / phone app).

Different harmony hubs should remain completely independent one of another and should not be both involved in a single zone in Roon - this will cause problem as Deep Harmony is not designed for this scenario and noone else I have come across does this. A normal use case for two hubs would be a hub upstairs controlling a system in a bedroom and another downstairs in the living room.

The power switch should be on your main hub and be part of the power on/off for the appropriate activity using the edit home control (in Harmony app) part of the activity.

**Comment by spottaaja1** [comment]
AFAIK there can be multiple activities active on one hub, if the activities 
in question are of 'home appliance type'. This is what I have on my second hub.


So, by my reasoning, Deep Harmony should be able to handle multiple 
activities with different states on one hub.


I feel that maybe I was unclear in explaining my setup, so here's a recap:


- two hubs: one in living room, another in office/game room
- living room hub is used with roon zone 'living room'
- office/game room hub is used with two roon zones: office/game room zone 
and music room zone
- office/game room hub can have multiple activities active at the same 
time: the one I choose for the office/game room and another I have for the 
music room
- when I play music in music room, roon should activate/deactivate the 
music room activity regardless of the office/game room activity being 
active or not.

I didn't quite get your suggestion on how to fix my setup so that music 
room would work too. Could you maybe elaborate a bit?
